/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jni_test_HelloWorld */

#ifndef _Included_com_jni_test_HelloWorld
#define _Included_com_jni_test_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_test_HelloWorld
 * Method:    getStringFromC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_test_HelloWorld_getStringFromC
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL Java_com_jni_test_HelloWorld_calculate
(JNIEnv * env, jobject obj, jint a, jint b);

JNIEXPORT jstring JNICALL Java_com_jni_test_HelloWorld_accessField
(JNIEnv * env, jobject obj);

JNIEXPORT jint JNICALL Java_com_jni_test_HelloWorld_accessStaticField
(JNIEnv * env, jobject obj);


JNIEXPORT jint JNICALL Java_com_jni_test_HelloWorld_accessMethod
(JNIEnv * env, jobject obj);

JNIEXPORT jstring JNICALL Java_com_jni_test_HelloWorld_accessStaticMethod
(JNIEnv * env, jobject obj);

JNIEXPORT jobject JNICALL Java_com_jni_test_HelloWorld_accessConstructor
(JNIEnv * env, jobject obj);

JNIEXPORT void JNICALL Java_com_jni_test_HelloWorld_accessNonvirtualMethod
(JNIEnv * env, jobject obj);

JNIEXPORT jobject JNICALL Java_com_jni_test_HelloWorld_chineseChars
(JNIEnv * env, jobject obj,jstring jstr);

JNIEXPORT void JNICALL Java_com_jni_test_HelloWorld_giveArray
(JNIEnv * env, jobject obj, jintArray array);

JNIEXPORT jintArray JNICALL Java_com_jni_test_HelloWorld_getArray
(JNIEnv * env, jobject obj,jint len);

JNIEXPORT void JNICALL Java_com_jni_test_HelloWorld_localRef
(JNIEnv * env, jobject obj);

JNIEXPORT void JNICALL Java_com_jni_test_HelloWorld_createGlobalRef
(JNIEnv * env, jobject obj);

JNIEXPORT jstring JNICALL Java_com_jni_test_HelloWorld_getGlobalRef
(JNIEnv * env, jobject obj);

JNIEXPORT void JNICALL Java_com_jni_test_HelloWorld_deleteGlobalRef
(JNIEnv * env, jobject obj);

JNIEXPORT void JNICALL Java_com_jni_test_HelloWorld_exception
(JNIEnv * env, jobject obj);

JNIEXPORT void JNICALL Java_com_jni_test_HelloWorld_cached
(JNIEnv * env, jobject obj);

JNIEXPORT void JNICALL Java_com_jni_test_HelloWorld_initIDs
(JNIEnv * env, jclass cls);

JNIEXPORT jstring JNICALL Java_com_jni_test_HelloWorld_encrypt
(JNIEnv * env, jobject obj,jstring jstr);

JNIEXPORT jstring JNICALL Java_com_jni_test_HelloWorld_decrypt
(JNIEnv * env, jobject obj, jstring jstr);

#ifdef __cplusplus
}
#endif
#endif
